//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVDatabase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationHints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationHints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSVDatabase.OperationHints", typeof(OperationHints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter record values separated by space.
        /// </summary>
        public static string Add_AskForRecord {
            get {
                return ResourceManager.GetString("Add_AskForRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter row index.
        /// </summary>
        public static string Add_AskForRow {
            get {
                return ResourceManager.GetString("Add_AskForRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not a valid command. Try something else or type &apos;help&apos;.
        /// </summary>
        public static string On_default {
            get {
                return ResourceManager.GetString("On default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:
        ///
        ///- add
        ///- read
        ///- remove
        ///- update
        ///
        ///- stats
        ///- help
        ///- exit
        ///
        ///Type one of the commands in order to start..
        /// </summary>
        public static string OnHelp {
            get {
                return ResourceManager.GetString("OnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is finished..
        /// </summary>
        public static string OnOperationFinished {
            get {
                return ResourceManager.GetString("OnOperationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter row index (or leave empty for all rows).
        /// </summary>
        public static string Read_AskForNullableInt {
            get {
                return ResourceManager.GetString("Read_AskForNullableInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter row index.
        /// </summary>
        public static string Remove_AskForRow {
            get {
                return ResourceManager.GetString("Remove_AskForRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter field value.
        /// </summary>
        public static string Update_AskForFieldValue {
            get {
                return ResourceManager.GetString("Update_AskForFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter row and column separated by space.
        /// </summary>
        public static string Update_AskForRowAndColumn {
            get {
                return ResourceManager.GetString("Update_AskForRowAndColumn", resourceCulture);
            }
        }
    }
}
